version: '3.8'

services:
  cpatl:
    build: .
    command: >
      sh -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code/
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:17-alpine
    volumes:
      - postgres_data:/db/lib/postgresql/data/
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
volumes:
  postgres_data:

